package POJO;
// Generated Jul 29, 2026 7:37:09 PM by Hibernate Tools 3.6.0



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String category;
     private double price;
     private String size;
     private String imageUrl;

    public Products() {
    }

	
    public Products(String name, double price) {
        this.name = name;
        this.price = price;
    }
    public Products(String name, String category, double price, String size, String imageUrl) {
       this.name = name;
       this.category = category;
       this.price = price;
       this.size = size;
       this.imageUrl = imageUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    



}


